### ISSUE TITLE
how to prepare the ufboot file

### ISSUE THREAD

**Issue by susutBu** [maxemil/ALE-pipeline#1]
Hey Schön:
    I have read this pipeline and your paper published in nc. And I think this pipeline are useful and convenient for ancestral reconstruction. But something puzzled me about how to prepare the ufboot file at the step of  preparation of ALE input. You mentioned that **"A sample of trees for a gene cluster (e.g. a bootstrap sample or mcmc sampled trees) in one file, one tree per line"**, can I understand  that just cat all the unfoot file of each gene family to a concat file ? such as "cat *ufboot > concat.ufboot". 
But I checked the "0KR93.ufboot" of your paper, it may not just a simple cat command. And I don't use the nextflow to run an ALE analysis, is that the reason?
cheers,
Bu

**Comment by maxemil** [comment]
Hej Bu, great that you find the pipeline useful! 
You should have one .ufboot file (if you use ultrafast bootstraps from IQ-tree for you sample, but you can also use mcmc output or 'real' bootstraps) per gene family. I just made the nextflow pipeline to process a large number of gene families conveniently. If you are interested in running ALE 'manually'. have a look at https://github.com/ssolo/ALE.
Hope that helps you forward!

**Comment by susutBu** [comment]
Hey Schön:
I'm sorry I didn't pick it up until now because of some problem. You reply have cleared up my confusion.
But another problem arose when I used your pipeline to analyse my data, If it's convenient to mention it here! the ETE3_Utils  and ETE3_styles module  mentioned in cleanSpeciesTree.py cannot be founded anywhere which resulted in the abort of the process. Do your have any idead baout this problem.
Thanks again
sincerely,
Bu

**Comment by maxemil** [comment]
Hej Bu,
Thanks for the comment! Indeed ETE3_Utils and ETE3_Styles were my private function libraries, so it could not work for you or anyone else... I added the relevant functions now and think it should now work as expected (the tests work at least). Let me know if this solves the problem for you as well!

**Comment by susutBu** [comment]
Hey Schön::
Thanks for your reply! The ETE3_Utils and ETE3_Styles worked very well after your fixing. unfortunately,  some other problems arosed when I testing. Firstly, one occured in this process "aleMlUndated (species_clean - testgene)" which maybe resulted by different ale version, but I dont know. I worked well after I edited main.nf file with replacing "{ale}" with "${species_tree}_${ale}" in line 143 to 145 of main.nf. Then, another question was occured in the last proccess--summmarizeDTLEvents, which raised a ValueError, which cannot convert float NaN to integer. Is this due to different versions of Pandas? Do you encounter any of these problems when running test data?
![image](https://user-images.githubusercontent.com/42882120/120329450-725c0300-c31e-11eb-80f0-c415156629a2.png)


[log.txt](https://github.com/maxemil/ALE-pipeline/files/6576483/log.txt)
